config/routes.rb
Rails.application.routes.draw do
  
  root to: 'timelines#index'

  devise_for :users
  
  
  resources :timelines do
    collection do
      post 'filter_by_user'
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
    belongs_to :user
    # dependent: :destroyを追加
    has_many   :replies, class_name: 'Timeline', foreign_key: 'reply_id', dependent: :destroy
    
    validates :message, presence: true, allow_blank: false
    
    scope :user_filter, -> user_id do
    # user_idパラメータがあればフィルターをかける
    where(user_id: user_id) if user_id.present?
  end
  
  scope :not_reply, ->  do
    # 返信でないデータを取得
    where(reply_id: nil)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # サムネイル画像にCarrierWaveで作成したUserThumnailUploaderを使用
  mount_uploader :thumbnail, UserThumbnailUploader
  
  validates :name, presence: true
  validates :agreement, presence: true, acceptance: {accept: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # 未ログイン状態でホーム画面にアクセスした場合に、ログイン画面にリダイレクトするようにする
  before_action :authenticate_user!
  
  # deviseのコントローラを実行するときは「configure_permitted_parameters」メソッドを実行する
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    #新規作成にname,thumbnail,agreementパラメータを含める
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :thumbnail, :agreement])
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    # メッセージ入力
    # @input_message = Timeline.new
    @input_message = params[:id] ? Timeline.find(params[:id]) : Timeline.new
    # タイムラインを取得
    # @timeline = Timeline.includes(:user).order('updated_at DESC')
    #--*********************** 修正後(2回目)***********************
    # @timeline = Timeline.includes(:user).user_filter(params[:filter_user_id]).order('updated_at DESC')
    #--*********************** 修正後(3回目) ***********************
    @timeline = Timeline.includes(:user).not_reply.user_filter(params[:filter_user_id]).order('updated_at DESC')
    # ユーザ一覧を取得
    @users = User.all
    
    if params[:reply_id]
      # 返信時は返信のタイムライン情報を取得
      @reply_timeline = Timeline.find(params[:reply_id])
    end
    
  end
  
  def create
    timeline = Timeline.new
    timeline.attributes = input_message_param
    timeline.user_id = current_user.id
    if timeline.valid? # バリデーションチェック
      timeline.save!
    else
      flash[:alert] = timeline.errors.full_messages
    end
    redirect_to action: :index
  end
  
  def update
    timeline = Timeline.find(params[:id])
    timeline.attributes = input_message_param
    if timeline.valid? # バリデーションチェック
      timeline.save!
    else
      flash[:alert] = timeline.errors.full_messages
    end
    # redirect_to action: :index
    # 下記に修正
    unless request.format.json?
      redirect_to action: :index
    else
      # ajaxの場合のレスポンス
      html = render_to_string partial: 'timelines/timeline', layout: false, formats: :html, locals: { t: timeline }
      render json: {timeline: html}
    end
  end
  
  def destroy
    timeline = Timeline.find(params[:id])
    timeline.destroy
    redirect_to action: :index
  end
  
  def filter_by_user
    if params[:filter_user_id].present?
      redirect_to action: :index, filter_user_id: params[:filter_user_id]
    else
      # フィルターなし
      redirect_to action: :index
    end
  end

  private
  def input_message_param
    params.require(:timeline).permit(:message, :reply_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
     # 自分の投稿か判定する
  def mypost?(timeline)
    timeline.user.id == current_user.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesMessenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <div class="logout_wrapper">
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </div>
<% end %>
  
<!--ログイン成功メッセージを共通レイアウトに表示させる-->
<p class="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/timelines/_timeline.html.erb
<%
  is_reply = false if is_reply.nil?
%>

<div class="per <%= 'mine' if t.user.id == current_user.id %>">
    <p class="icon">
        <!-- サムネイルの設定確認 -->
        <% if t.user.thumbnail? %>
            <%= image_tag t.user.thumbnail.url %>
        <% else %>
            NO IMAGE
        <% end %>
    </p>
    <%= simple_format t.message, class: 'message' %>
    <!--** 自作したヘルパーメソッドを呼ぶ ******-->
    <!--** 自分の投稿の場合は編集ボタンを追加 **-->
    <% if mypost?(t) %>
        <div class="operation">
            <!-- 自分の投稿の場合、編集ボタンを表示 -->
            <%= link_to root_path(id: t.id, message: t.message) do %>
                <%= button_tag 'Edit', class: 'btn btn-info' %>
            <% end %>
            <%= button_to 'Del', timeline_path(t), method: :delete, class: 'btn btn-danger', data: {confirm: '削除してよろしいですか？'}  %>
        </div>
    <% else %>
        <!-- 他人の投稿の場合、Reボタンを表示 -->
        <%= link_to root_path(reply_id: t.id) do %>
        <%= button_tag 'Re', class: 'btn btn-info' %>
        <% end %>
    <% end %>
</div>
<% t.replies.each do |r| %>
  <%= render 'timelines/timeline', t: r, is_reply: true %>
<% end %>

app/views/timelines/index.html.erb
<div class="wrapper timeline_wrapper">

  <!-- メッセージ入力 -->
  <div class="input">
    <!--<　%= form_for @input_message do |f| %>-->
    <%= form_for @input_message, remote: true, html: {class: 'input_message_form'}, format: :json, authenticity_token: true do |f| %>
      <div class="form-group">
        <%= f.label :message %>
        <!--** 編集中の場合は場合はメッセージを表示 **-->
        <% if @input_message.persisted? %>
          編集中
          <% elsif @reply_timeline %>
          <%= @reply_timeline.user.name %>の「<%= truncate(@reply_timeline.message, length: 7) %>」に返信
        <% end %>
        <br/>
        <%= f.text_area :message, class: 'form-control', rows: 3 %>
      </div>
      <div class="actions clearfix">
        <div class="alert">
          <% if flash[:alert] %>
            <% flash[:alert].each do |message| %>
              <p class="alert"><%= message %></p>
            <% end %>
          <% end %>
        </div>
        <div class="post">
          <!--** 編集中は編集をキャンセルするボタンを表示 **-->
          <!--修正前-->
          <!--< % if @input_message.persisted? % >-->
          <!--修正後-->
          <% if @input_message.persisted? || @reply_timeline %>
            <%= link_to root_path do %>
              <%= button_tag 'Cancel', class: 'btn btn-default' %>
            <% end %>
          <% end %>
          <!--<　%= f.submit 'Post', class: 'btn btn-primary' %>-->
          <%= f.submit 'Post', class: 'btn btn-primary post' %>
          <%= f.submit 'AjaxPost', class: 'btn btn-primary ajaxpost' %>
        </div>
      </div>
      <%= f.hidden_field :reply_id, value: @reply_timeline.id if @reply_timeline %>
    <% end %>
  </div>
  
  <div class="user_filter">
    <%= form_tag filter_by_user_timelines_path do |f| %>
      <div class="form-group">
        <label>ユーザフィルター</label><br/>
        <%= select_tag :filter_user_id, options_for_select(@users.map { |m| [m.name, m.id] }, params[:filter_user_id]), prompt: 'フィルターなし', class: 'form-control' %>
      </div>
      <div class="actions">
        <%= submit_tag 'Apply', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  
<!-- タイムライン -->
  <div class="timeline">
    <% @timeline.each do |t| %>
      <%= render 'timelines/timeline', t: t %>
    <% end %>
  </div>
</div>